### PR TITLE
fixes & improvements

### LINKED ISSUE #49: iplocation: consider embedding database

### PR DESCRIPTION
**Pull request by jsign**
A bunch of fixes and improvements based on running the dashboard, not much of this bugs tracked since discovered and fixed right away. Some more details in the comments.

The only tracked one was Closes #49 , which seems no to be necessary since I'm copying it in the Dockerfile, so it's kind of embedded (not in the binary, but in the running image).

### CODE REVIEW

File: api/server/server.go [hunk 1]
```diff
@@ -83,7 +84,7 @@ func NewServer(conf Config) (*Server, error) {
 	}
 	dm := deals.New(txndstr.Wrap(ds, "dealmodule"), c)
 
-	ip2l := ip2location.New([]string{"ip2location-ip4.bin"}) // ToDo: Flags or embed
+	ip2l := ip2location.New([]string{"./ip2location-ip4.bin"})
```
Comment (jsign) [inline api/server/server.go]: The _ip2location-ip4.bin_ file is `COPY`ed in the Dockerfile in the same directory that the entroypoint.

File: api/server/server.go [hunk 2]
```diff
@@ -184,4 +186,5 @@ func (s *Server) Close() {
 		log.Errorf("error when closing datastore: %s", err)
 	}
 	s.closeLotus()
+	s.ip2l.Close()
```
Comment (jsign) [inline api/server/server.go]: Should close the `ip2l` service.

File: docker/Makefile [hunk 3]
```diff
@@ -1,4 +1,5 @@
 LT = $(shell cat ~/.lotus/token)
+#LT = $(shell docker exec lotustest cat /root/.lotus/token)
```
Comment (jsign) [inline docker/Makefile]: Leaved this since in remote instance the Lotus node is running in docker.

File: docker/grafana/provisioning/dashboards/TextileFC.json [hunk 4]
```diff
@@ -513,17 +513,17 @@
         "showThresholdLabels": false,
```
Comment (jsign) [inline docker/grafana/provisioning/dashboards/TextileFC.json]: Grafana fixes/improvements.

File: fchost/fchost.go [hunk 5]
```diff
@@ -32,7 +36,7 @@ func New() (*FilecoinHost, error) {
 		return nil, err
 	}
 
-	dht, err := dht.New(ctx, h)
+	dht, err := dht.New(ctx, h, dhtopts.Protocols("/lotus/kad/1.0.0"))
```
Comment (jsign) [inline fchost/fchost.go]: Seems that now that libp2p hosts aren't running in a private network as before, they have their ProtocolID for DHT.
Took some time to figure out why DHT wasn't working...

File: fchost/fchost.go [hunk 6]
```diff
@@ -19,8 +22,9 @@ var (
 
 // FilecoinHost is a libp2p host connected to the FC network
 type FilecoinHost struct {
-	host.Host
-	dht *dht.IpfsDHT
+	ping *ping.PingService
+	h    host.Host
+	dht  *dht.IpfsDHT
```
Comment (jsign) [inline fchost/fchost.go]: `host.Host` isn't embedded anymore, so less power for users of `FilecoinHost`.
Preferred this way and implement as public methods whatever they need.

File: fchost/fchost.go [hunk 7]
```diff
@@ -57,6 +63,25 @@ func (fh *FilecoinHost) Bootstrap() error {
 	return nil
 }
 
+func (fc *FilecoinHost) Ping(ctx context.Context, pid peer.ID) bool {
```
Comment (jsign) [inline fchost/fchost.go]: Used so the Metadata Index of Miners can discover if a miner responds to the Ping protocol, to decide if it's online or not.

File: fchost/fchost.go [hunk 8]
```diff
@@ -57,6 +63,25 @@ func (fh *FilecoinHost) Bootstrap() error {
...
+	r := <-fc.ping.Ping(ctx, pid)
+	return r.Error == nil
+}
+
+func (fc *FilecoinHost) GetAgentVersion(pid peer.ID) string {
```
Comment (jsign) [inline fchost/fchost.go]: Abstracted AgentVersion fetching info. 
In case we're interested in an extra thing, it could receive the key as param and be generic.

File: index/miner/meta.go [hunk 9]
```diff
@@ -2,11 +2,12 @@ package miner
 
 import (
```
Comment (jsign) [inline index/miner/meta.go]: Mostly enabling some capped parallelization to discover metadata about miners. Capped at 100 max at a time, could be played bit.

File: index/miner/metrics.go [hunk 10]
```diff
@@ -7,15 +7,22 @@ import (
 )
 
 var (
```
Comment (jsign) [inline index/miner/metrics.go]: Yet some more accurate renamings.

File: index/slashing/slashing.go [hunk 11]
```diff
@@ -243,9 +243,8 @@ func epochPatch(ctx context.Context, c API, pts *types.TipSet, ts *types.TipSet)
 			}
 			mas, ok := as.State.(map[string]interface{})
 			if !ok {
-				panic("read state should be a map interface result")
+				log.Debugf("read state should be a map interface result: %#v", as.State)
```
Comment (jsign) [inline index/slashing/slashing.go]: For some reason this case started happening. Opted to not be fatal, log, and move on.
Basically is returning `nil`, but not a typed `map[string]interface{}` nil or empty thing.

File: iplocation/ip2location/ip2location.go [hunk 12]
```diff
@@ -41,18 +45,25 @@ func New(paths []string) *IP2Location {
...
+			continue
+		}
+		ip, _, err := net.SplitHostPort(ipport)
 		if err != nil {
+			log.Debugf("error parsing ip/port from %s: %s", ipport, err)
 			continue
 		}
 		r := ip2location.Get_all(ip)
-		if r.Country_long != "" && r.Latitude != 0 && r.Longitude != 0 {
+		if r.Country_long != "" || (r.Latitude != 0 && r.Longitude != 0) {
```
Comment (jsign) [inline iplocation/ip2location/ip2location.go]: Any of the country or coords should be enough to return something.
